phantomcyber/phantom-apps

Apps/phtwitter/readme.html
Adding license details in the readme.html
=> Twitter: Adding license details in the readme.html

Apps/phokta/okta.json, Apps/phokta/okta_connector.py
This pull request shall add additional capabilities (action named  **send push notification**) to `phokta` app.
Refer: #147 and `FDSE-478`
=> Added: action 'send push notification' - FDSE-478

Apps/phdossier/readme.html
Adding the readme.html to document the standard port value.
=> PAPP-8988: Adding readme.html

Apps/phproofpoint/proofpoint.json, Apps/phproofpoint/proofpoint_connector.py
=> Added and asset config param to allow the ingestion window to be customized

Apps/phcrowdstrikeoauth/__init__.py, Apps/phcrowdstrikeoauth/crowdstrike_assign_hosts.html, Apps/phcrowdstrikeoauth/crowdstrike_remove_hosts.html, Apps/phcrowdstrikeoauth/crowdstrike_view.py, Apps/phcrowdstrikeoauth/crowdstrikeoauthapi.json, Apps/phcrowdstrikeoauth/crowdstrikeoauthapi_connector.py, Apps/phcrowdstrikeoauth/crowdstrikeoauthapi_consts.py, Apps/phcrowdstrikeoauth/readme.html
Done with compatibility changes. Confirmed testplaybook is working the same when running on both python versions.
=> Python 2&3 compatibility changes

Apps/phawssecurityhub/awssecurityhub.json, Apps/phawssecurityhub/awssecurityhub_connector.py, Apps/phawssecurityhub/awssecurityhub_consts.py, Apps/phawssecurityhub/awssecurityhub_view.py
Changed main module, copyright dates, last tested versions...
=> PAPP-9054 more changes for py2 and py3 compatibility

Apps/phreversinglabs/__init__.py
Accidentally missed this file on last update.
=> PAPP-9270 updated copyright notice

Apps/phtaniumrest/taniumrest_connector.py, Apps/phtaniumrest/taniumrest_consts.py
=> Taniumrest runquery fix

Apps/phskypebusiness/__init__.py, Apps/phskypebusiness/readme.html, Apps/phskypebusiness/skypeforbusiness.json, Apps/phskypebusiness/skypeforbusiness_connector.py, Apps/phskypebusiness/skypeforbusiness_consts.py
Python 2 to 3 changes and bug fixes
=> Skype: Python 2 to 3 changes and bug fixes

Apps/phawssecurityhub/awssecurityhub_connector.py
=> PAPP-9928 security hub sqs ingestion failing due to unexpected event types in queue

Apps/phcrowdstrikeoauth/readme.html
Crowdstrike OAuth: Updated the readme file
=> Crowdstrike OAuth: Updated the readme file

Apps/phcofensetriage/cofensetriage_connector.py
Cofense Triage: Bug Fix for PAPP-11009
=> Cofense Triage: Bug Fix for PAPP-11009

Apps/phwindowsdefenderatp/__init__.py, Apps/phwindowsdefenderatp/readme.html, Apps/phwindowsdefenderatp/windowsdefenderatp.json, Apps/phwindowsdefenderatp/windowsdefenderatp_connector.py, Apps/phwindowsdefenderatp/windowsdefenderatp_consts.py
This PR is for Initial MC conversion. Contains changes from `next` branch and mc conversion script.
=> PAPP-10823: Initial MC Conversion for windowsdefenderatp

Apps/phwindowsdefenderatp/windowsdefenderatp.json, Apps/phwindowsdefenderatp/windowsdefenderatp_connector.py, Apps/phwindowsdefenderatp/windowsdefenderatp_consts.py
Implementing client_credentials grant_type for testing actions
=> Using client_credentials as grant type

Apps/phwinrm/winrm.json, Apps/phwinrm/winrm_connector.py
Utilize asset config endpoint as a default if not provided in an action.
=> PAPP-9856 Set default endpoint with asset

Apps/phchronicle/chronicle_consts.py
Chronicle: Minor update in the error message
=> Chronicle: Minor update in the error message

Apps/phcrowdstrikeoauth/crowdstrikeoauthapi_connector.py
=> Crowdstrike OAuth: Fix as per PAPP-11647

Apps/phcrowdstrikeoauth/crowdstrikeoauthapi_connector.py
=> Crowdstrike OAuth: Bug fix as per PAPP-11657

Apps/phhaveibeenpwned/__init__.py, Apps/phhaveibeenpwned/haveibeenpwned.json
updated copyright info in init.py and json file to avoid failure in apps test pipeline
=> PAPP-11528-updated copyright information

Apps/phhaveibeenpwned/haveibeenpwned_consts.py
Added Unauthorized code in constants to resolve the test connectivity issue
=> PAPP-11518-resolved test connectivity issue

.github/CONTRIBUTING.md
- Describe how to trigger scans for pull requests.
- Describe the suite of tests/checks that are run against pull requests.
=> Add info about automated checks for submissions

Apps/phhaveibeenpwned/haveibeenpwned.json, Apps/phhaveibeenpwned/haveibeenpwned_connector.py, Apps/phhaveibeenpwned/haveibeenpwned_consts.py
- Updated license text to avoid failure in pipeline
- Moved constants from connector file to consts file
=> PAPP-11528 updated license info in json file and moved constants

Apps/phcofensetriage/cofensetriage.json, Apps/phcofensetriage/cofensetriage_connector.py, Apps/phcofensetriage/cofensetriage_consts.py, Apps/phcofensetriage/readme.html, Apps/phcofensetriage/todo.txt
Cofense Triage[PAPP-11335] Community app submission with bugs fixes
=> Cofense Triage[PAPP-11335] Community app submission with bugs fixes

.github/workflows/test-pr.yml, Apps/phsplunkitsi/README.md, Apps/phsplunkitsi/splunkitsi.json, Apps/phsplunkitsi/splunkitsi_connector.py, Apps/phsplunkitsi/splunkitsi_consts.py
-  WIP: SplunkItSi(PAPP-11321) Community app update with bug fixes
- Please take a note that I have changed the phantom version from 4.6 to 4.8 under the compatibility section in readme.md file as we are releasing the app with minimum phantom version set to 4.8.24304
=> SplunkItSi(PAPP-11321) Community app update with bug fixes

Apps/phphishtank/phishtank_connector.py
Test Pull Request to for testing GitHub workflows against a pull request from a forked repo.
=> IGNORE: Test Pull Request From Fork

Apps/phsymantecmc/symantecmanagementcenter_connector.py
Symantecmc(PAPP-11269): Minor Changes regarding Exception handling for Unicode
=> Symantecmc(PAPP-11269): Minor Changes regarding Exception handling for Unicode

README.md
=> Updating copy to be consistent

Apps/phsmime/__init__.py, Apps/phsmime/readme.html, Apps/phsmime/smime_connector.py, Apps/phsmime/smime_consts.py
- Added Apache 2.0 license in .py and .html files
- Added licensing details for wheel files
=> SMime(PAPP-9590): Minor change in Licensing Details

Apps/phphishtank/phishtank.json, Apps/phphishtank/phishtank_connector.py
This PR contains python 2to3 compatible changes and the JSON file updates.
=> Phishtank: PAPP-12101: Python 2to3 conversion

Apps/phcuckoo/cuckoo.json
Cuckoo: Updating the publisher to 'Splunk' as this a certified application
=> Cuckoo: Updating the publisher to 'Splunk' as this a certified application

Apps/phokta/okta.json, Apps/phokta/okta_connector.py, Apps/phokta/okta_consts.py
This PR contains python 2to3 compatible changes and the JSON file updates.
=> Okta: PAPP-12229: Python 2to3 conversion

Apps/phhaveibeenpwned/haveibeenpwned.json, Apps/phhaveibeenpwned/haveibeenpwned_connector.py
Added dev best practices for Have I been pwned
=> Added dev best practices for Have I been pwned

Apps/phairwatch/airwatch.json
Airwatch(PAPP-10078): Updating main_module to .py in json
=> Airwatch(PAPP-10078): Updating main_module to .py in json

Apps/phokta/okta.json, Apps/phokta/okta_connector.py
Handling the send push notification actions' workflow for sms and token:software:totp factortypes
=> Okta: PAPP-12934: Handling the send push notification exceptions

Apps/phhaveibeenpwned/haveibeenpwned.json, Apps/phhaveibeenpwned/haveibeenpwned_connector.py
Changes related to default value of truncate, added example values for summary
=> Have I been Pwned: PAPP-13061 Changes related to default value 

Apps/phwinrm/parse_callbacks.py, Apps/phwinrm/readme.html, Apps/phwinrm/winrm.json, Apps/phwinrm/winrm_connector.py, Apps/phwinrm/winrm_consts.py
WIP: WinRM: Bug fixes and Enhancement for PAPP-11891
=> WinRM: Bug fixes and Enhancement for PAPP-11891

Apps/phawsiam/awsiam.json
AWS IAM: Upgrading the app version
=> AWS IAM: Upgrading the app version

Apps/phproofpoint/__init__.py, Apps/phproofpoint/proofpoint.json, Apps/phproofpoint/proofpoint_connector.py, Apps/phproofpoint/proofpoint_consts.py
Proofpoint TAP: Updating license string for release
=> Proofpoint TAP: Updating license string for release

Apps/phawslambda/__init__.py, Apps/phawslambda/awslambda.json, Apps/phawslambda/awslambda_connector.py, Apps/phawslambda/awslambda_consts.py, Apps/phawslambda/awslambda_invoke.html, Apps/phawslambda/awslambda_view.py
Updates json file
Currently tests are failing as this PR is dependent on [MR](https://cd.splunkdev.com/phantom/app_release/-/merge_requests/962)
=> AWSLambda[PAPP-13424]:  JSON changes

Apps/phnessus/readme.html
Updated the readme file of Nessus to include the commonly used service ports based on standard guidelines of [IANA ORG]( https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml)
=> Nessus: Updated the readme file

Apps/phcrowdstrikeoauth/__init__.py, Apps/phcrowdstrikeoauth/crowdstrike_assign_hosts.html, Apps/phcrowdstrikeoauth/crowdstrike_create_session.html, Apps/phcrowdstrikeoauth/crowdstrike_get_indicator.html, Apps/phcrowdstrikeoauth/crowdstrike_get_user_roles.html, Apps/phcrowdstrikeoauth/crowdstrike_hunt_view.html, Apps/phcrowdstrikeoauth/crowdstrike_list_custom_indicators.html, Apps/phcrowdstrikeoauth/crowdstrike_list_incident_behaviors.html, Apps/phcrowdstrikeoauth/crowdstrike_list_incidents.html, Apps/phcrowdstrikeoauth/crowdstrike_process_list_view.html, Apps/phcrowdstrikeoauth/crowdstrike_remove_hosts.html, Apps/phcrowdstrikeoauth/crowdstrike_set_status_view.html, Apps/phcrowdstrikeoauth/crowdstrike_update_indicator.html, Apps/phcrowdstrikeoauth/crowdstrike_upload_indicator.html, Apps/phcrowdstrikeoauth/crowdstrike_view.py, Apps/phcrowdstrikeoauth/crowdstrikeoauthapi.json, Apps/phcrowdstrikeoauth/crowdstrikeoauthapi_connector.py, Apps/phcrowdstrikeoauth/crowdstrikeoauthapi_consts.py, Apps/phcrowdstrikeoauth/parse_cs_events.py, Apps/phcrowdstrikeoauth/readme.html
WIP: CrowdStrikeOAuthAPI[PAPP-13500]: Bug fixation
=> CrowdStrikeOAuthAPI[PAPP-13500]: Bug fixation

Apps/phawsathena/__init__.py, Apps/phawsathena/athena.json, Apps/phawsathena/athena_connector.py, Apps/phawsathena/athena_consts.py, Apps/phawsathena/athena_view.py, Apps/phawsathena/readme.html, Apps/phawsathena/run_query.html
Python 2to3 conversion and json changes.
This MR depends on 
- expected failure [MR](https://cd.splunkdev.com/phantom/app_release/-/merge_requests/988)
=> AWS Athena[PAPP-13583] Python 2to3 and json changes

Apps/phslack/slack.json, Apps/phslack/slack_connector.py, Apps/phslack/slack_consts.py
Expose Slack's reaction feature as an action
=> Add 'add reaction' action for reacting to Slack messages

Apps/phscreenshotmachine/ssmachine_connector.py
After referring to ticket [PPS-25211](https://jira.splunk.com/browse/PPS-25211) and performing QA related checks, we got to know that add_attachment API is deprecated.
Hence we replaced it with the new API "vault_add".
After testing we found that even though "add_attachement" is deprecated, it is still working on 4.10, still, we updated the code to use the newest API.
=> Screenshot Machine: PAPP-14436: Deprecated API change

Apps/phdigitalshadows/digital_shadows.json
Upgraded the Major App Version to 2 as the app has been converted to python 3 from python 2.7
=> DigitalShadows(PAPP-11277): App Version Upgrade

Apps/phsixgilldarkfeed/sixgilldarkfeed.json
Updating the license in the JSON file
=> Sixgill Darkfeed: Updating the license in the JSON file

Apps/phciscoumbrella/readme.html
Cisco Umbrella: Updating readme.html file for the app
=> Cisco Umbrella: Updating readme.html file for the app

Apps/phpaloaltocortexxdr/paloaltocortexxdr.json, Apps/phpaloaltocortexxdr/paloaltocortexxdr_connector.py
Palo Alto Cortex XDR: Handled BugFix
=> paloaltocortexxdr(PAPP-13698): Handled BugFix

.github/CONTRIBUTING.md, Apps/phsmime/smime.json, Apps/phvisualping/visualping.json
- Add a new section to indicate the contributor should add their name to "contributors" in the app JSON.
- Update automated check information in the guide based on its latest state.
- Add contributors to SMIME and VisualPing apps.
=> Update CONTRIBUTING.md with updated process details

Apps/phsentinelone/__init__.py, Apps/phsentinelone/readme.html, Apps/phsentinelone/sentinelone.json, Apps/phsentinelone/sentinelone_connector.py, Apps/phsentinelone/sentinelone_consts.py, Apps/phsentinelone/sentinelone_utilities.py
=> SentinelOne(PAPP-13608): Updated license

Apps/phsentinelone/readme.html
Added playbook backward compatibility in the readme file
=> SentinelOne(PAPP-13608): Added playbook backward compatibility

Apps/phawslambda/awslambda.json, Apps/phawslambda/awslambda_connector.py
Added 'remove permission' action for use with automated testing.
=> PAPP-14755 added 'remove permission' action

Apps/phcarbonblackresponse/carbonblack.json, Apps/phcarbonblackresponse/carbonblack_connector.py, Apps/phcarbonblackresponse/carbonblack_consts.py, Apps/phcarbonblackresponse/query_results.html
Carbon Black Response: PAPP-14877: Bug fixes
=> Carbon Black Response: PAPP-14877: Bug fixes

Apps/phcofensetriage/__init__.py, Apps/phcofensetriage/cofensetriage.json, Apps/phcofensetriage/cofensetriage_connector.py, Apps/phcofensetriage/cofensetriage_consts.py, Apps/phcofensetriage/default_timezones.py, Apps/phcofensetriage/readme.html
> Version-2.0.0 March 01, 2021
- Compatibility changes for Python 3 support
- Fixed artifacts ingestion for existing container
- Handled exception for large values of max_result parameter
- Removed API token displaying in the error message for incorrect email value
=> Cofense Triage app update

Apps/phsignalfx/readme.html, Apps/phsignalfx/signalfx.json, Apps/phsignalfx/signalfx_consts.py
Added latest_tested_version in Json, Minor changes in readme
=> Added latest_tested_version in json

Apps/phradar/radar_get_notes.html, Apps/phradar/radar_view.py
Issue providing context for PR:
https://github.com/phantomcyber/phantom-apps/issues/547
=> phradar v1.0.1 bug fix 

Apps/phredcanary/redcanary.json, Apps/phredcanary/redcanary_connector.py
These actions allow a user to acknowledge and mark a detection as remediated
=> Adding 2 new actions

Apps/phgcloudiam/googlecloudiam.json
Updating contains for action parameters
=> Google Cloud IAM: Updating contains for action parameters

Apps/phdigitalguardianarc/digitalguardianarc.json, Apps/phdigitalguardianarc/digitalguardianarc_connector.py
Fixed an issue with watchlists not working correctly
Also added mapping for Classification data
=> Digitalguardian Watchlist issue fix

Apps/phcrowdstrikeoauth/crowdstrikeoauthapi.json, Apps/phcrowdstrikeoauth/crowdstrikeoauthapi_connector.py
added error handling in case custom scripts are disabled in settings when executing run_admin_command action to prevent infinite loop
=> PAPP-16588 - infinite loop "run admin command" action

Apps/phdeepsight/deepsight.json
modified package_name in JSON to identify this app as the new Accenture variant to alleviate issues downstream with app release pipelines
=> PAPP-16359 - modified package_name in app JSON

Apps/phwindowsdefenderatp/windowsdefenderatp_connector.py
fixed issue where symlinks would cause an error trying to load/save the state file when using realpath()
=> PAPP-16689 PAPP-16682

Apps/phjira/jira.json
Upgrading Minor version in Jira App for release
=> Jira: Upgrading minor version for release

Apps/phredcanary/redcanary.json, Apps/phredcanary/redcanary_connector.py, Apps/phredcanary/redcanary_consts.py
* Adding 2 new actions
* Making sure action output is sequential
* Add param ordering
Co-authored-by: Matt Hastings <>
=> Red Canary: Adding 2 new actions (#563)

Apps/phforescoutcounteract/forescoutcounteract.json, Apps/phforescoutcounteract/list_host_properties.html, Apps/phforescoutcounteract/list_policies.html
Added "mac address" in the contains
=> Forescout: PAPP-15916 Added "mac address" in the contains

Apps/phkasperskyti/kasperskythreatintelligence.json, Apps/phkasperskyti/kasperskythreatintelligence_connector.py, Apps/phkasperskyti/kasperskythreatintelligence_consts.py, Apps/phkasperskyti/readme.html
Kaspersky TI[PAPP-16648]: Added exception handling and minor changes
=> Kaspersky TI[PAPP-16648]: Added exception handling and minor changes

Apps/pharcsight/arcsight.json, Apps/pharcsight/arcsight_connector.py, Apps/pharcsight/arcsight_consts.py, Apps/pharcsight/display_results.html
The connecter makes a response to `/getResourceById` to get a response to pass to `add_data()`. 
Unless the response property `numberOfOccurrences` from this API call is spelt incorrectly, there is a typo in the output JSON that would cause this response to be blank when used in a Playbook. I don't have access to their API or docs to know if that is true or not.
=> Correct name of prop in action_result.data

Apps/phawssecurityhub/awssecurityhub_connector.py
=> PAPP-17507 AWS SecurityHub fixed parameter passing to client method

Apps/phcofensetriagev2/cofensetriagev2.json
- Updated application description referencing Cofense Triage v2 API, no functional changes
=> Cofense Triage v2 : App update

Apps/phcofensetriagev2/cofensetriagev2.json
=> Cofense Triage V2: Resolve unicode encode issue

Apps/phawssecurityhub/awssecurityhub.json
=> AWS Security Hub: PAPP-17507 - made access and secret keys optional

Apps/phcheckpointfirewall/checkpoint.json
=> PAPP-18146 Checkpoint: Updating major app version

Apps/phwindowsdefenderatp/readme.html, Apps/phwindowsdefenderatp/windowsdefenderatp.json, Apps/phwindowsdefenderatp/windowsdefenderatp_connector.py, Apps/phwindowsdefenderatp/windowsdefenderatp_consts.py, Apps/phwindowsdefenderatp/windowsdefenderatp_list_alerts.html, Apps/phwindowsdefenderatp/windowsdefenderatp_view.py
WindowsDefenderATP: PAPP-18940: Added custom view for the 'list alerts' action
- The 'list alerts' action has a table view widget. For one alert, we can see multiple identical rows in the table widget.
- There was a behaviour change in the API and we were getting different messages in the response. Due to this token regeneration flow was affected.
- Replaced table view with a custom view. Now only one entry will be shown for each alert in the data.
- Fixed a message in the condition to fix the token regeneration when the access token is expired.
Jenkins job for the Test Pipeline: https://jenkins.engineering.phantom.us:8443/view/Apps/job/opensource_and_community_app_test/506/console
=> WindowsDefenderATP: PAPP-18940: Bug fixes

Apps/phawsguardduty/awsguardduty.json, Apps/phawsguardduty/awsguardduty_connector.py
=> AWS GuardDuty: PAPP-17489 bug fixes

Apps/phawsguardduty/awsguardduty_connector.py
=> AWS GuardDuty: PAPP-17489 fixed typo

Apps/phcrowdstrikeoauth/crowdstrikeoauthapi.json
=> CrowdStrike OAuth: App version bump

Apps/phgreynoise/greynoise_connector.py
=> GreyNoise[PAPP-18985]: Resolving the pipeline issue

Apps/phpanorama/panorama.json
- Add STATUS column to RunQuery action.
- The widget for the RunQuery action does not include "Status" column.
- The widget for the RunQuery action should include "Status" column. This will help improve our testing - we can check for the status for cases where we have results / no result.
- With this change, our tests will fully support Version 10.1.0
* Container: https://10.1.66.58/mission/403/analyst/timeline
=> Panorama: Feature - Add "Status" column to the widget of RunQuery action

Apps/phawswafv2/awswafv2_connector.py
=> AWS WAFv2: PAPP-17524 fixed bug with setting region during assume role

Apps/phmimecast/mimecast_connector.py
=> PAPP-15546: Mimecast: Bug Fix: Initializing global variables to avoid attribute error in finalize block in case of corrupted state file

Apps/phpanorama/panorama.json
=> Panorama: App bump to push commit for build_phantom job

Apps/phurlvoid/urlvoid.json
=> PAPP-19356 URLVoid: Community app release

Apps/phawsiam/awsiam_connector.py
=> PAPP-17441 removed unnecessary check in test connectivity

Apps/phaxoniuscybersecurityassetmanagement/axoniuscybersecurityassetmanagement.json, Apps/phaxoniuscybersecurityassetmanagement/axoniuscybersecurityassetmanagement_connector.py, Apps/phaxoniuscybersecurityassetmanagement/axoniuscybersecurityassetmanagement_consts.py
Adding the ability to add additional fields to the returned object. This affects all calls except those using saved queries.
We are adding the ability list any number of additional fields to include in the returned object from Axonius. All actions that do not operate off of saved queries will now have a new parameter called "additional fields". This is a comma separated list of Axonius fields in full dotted notation.
=> phaxoniuscybersecurityassetmanagement: feature - Adding ability to include addition fields in all non saved query calls.

Apps/phawsiam/awsiam.json
=> PAPP-17438 AWS IAM: App version bump up

Apps/phawswafv2/awswafv2.json
=> PAPP-17523 AWS WAFv2 version bump

Apps/phawsathena/athena.json
=> PAPP-17551-AWS Athena version bump

Apps/phciscowebex/ciscowebex.json, Apps/phciscowebex/ciscowebex_connector.py, Apps/phciscowebex/readme.html
=> cisco webex documentation change

Apps/phawssecurityhub/awssecurityhub.json
=> PAPP-17508 AWS SecHub bump of app version

Apps/phawscloudtrail/awscloudtrail.json
=> PAPP-17454 AWS CloudTrail bumped app version

Apps/phchronicle/chronicle.json, Apps/phchronicle/chronicle_connector.py
- Fixed a bug to trigger active playbooks for every ingested artifact.
- Currently, the active playbooks are triggered only for the last batch of ingested artifacts where multiple batches of artifacts are ingested in a single run.
- The active playbooks are triggered for all the batches of ingested artifacts.
=> Chronicle: Fixed a bug for the run automation flag

Apps/phawslambda/awslambda.json
=> PAPP-17643 AWS Lambda updated app version and latest tested version

Apps/phdigicert/digicert.json, Apps/phdigicert/digicert.svg, Apps/phdigicert/digicert_dark.svg
- Adding Required datapaths
- Adding height & width in logo file
=> DigiCert: Adding required datapaths and other minor changes

Apps/phgsgmail/gsgmail.json
=> GS Gmail: App version bump for the new release

Apps/phazurevmmanagement/microsoftazurevmmanagement.json, Apps/phazurevmmanagement/microsoftazurevmmanagement_connector.py, Apps/phazurevmmanagement/microsoftazurevmmanagement_consts.py, Apps/phazurevmmanagement/readme.html
=> Microsoft Azure Compute: added validator for ipv6 contains

Apps/phthehive/readme.html, Apps/phthehive/thehive.json, Apps/phthehive/thehive_connector.py, Apps/phthehive/thehive_consts.py, Apps/phthehive/thehive_display_get_observables.html
* This is adding an action to add a task log entry. Task logs in theHive are how tasks have notes added to them, so this will allow phantom to add a note to a task. 
* This is adding the code for the action as well as the action into the JSON.
* Currently the app does not have an action to add a task log, so I am adding that action.
* This will add the message parameter to a task log entry in the task provided by the task parameter.
=> TheHive: Add Action - Add create_task_log action to app

Apps/phscreenshotmachine/readme.html, Apps/phscreenshotmachine/ssmachine.json, Apps/phscreenshotmachine/ssmachine_connector.py, Apps/phscreenshotmachine/ssmachine_consts.py
=> Screenshot machine: Feature - Added cache limit config parameter

Apps/phphishtank/PhishTank.postman_collection.json, Apps/phphishtank/__init__.py, Apps/phphishtank/phishtank.json, Apps/phphishtank/phishtank_connector.py, Apps/phphishtank/phishtank_consts.py
=> Postman collection for PhishTank app

Apps/phpassivetotal/exclude_files.txt, Apps/phpassivetotal/passive total.postman_collection.json
=> Passivetotal: Postman | PAPP-20940 | added postman collection for passive total app

Apps/phcheckpointfirewall/checkpoint.json, Apps/phcheckpointfirewall/checkpoint_connector.py
Added new 'add host' action
- Any specific code change or test case points which must be addressed/reviewed at the time of GA …
=> Check Point Firewall: PAPP-9260 Add 'add host' action
